ClusterName=ResearchCluster

ControlMachine=localhost

SlurmUser=root

AuthType=auth/munge

StateSaveLocation=/var/spool/slurmctld

SlurmdSpoolDir=/var/spool/slurmd

NodeName=localhost CPUs=4 RealMemory=4000 State=UNKNOWN

PartitionName=debug Nodes=ALL Default=YES MaxTime=INFINITE State=UP
