---
- name: Install HPC lab dependencies
  hosts: all
  become: true
  tasks:
    - name: Install required packages
      ansible.builtin.package:
        name:
          - slurm-wlm
          - htop
          - python3
        state: present
